# Generated by Django 4.0.3 on 2022-03-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMI_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female')])),
                ('image', models.ImageField(upload_to='images/')),
                ('bmi', models.FloatField()),
                ('fat', models.FloatField()),
            ],
        ),
    ]
